import puppeteer from 'puppeteer-core';
import {writeFile,mkdir} from 'node:fs/promises';import {resolve} from 'node:path';import assert from 'node:assert/strict';import {previewServer} from './serve.mjs';
await mkdir('work/v22/test-output',{recursive:true});await mkdir('deliverables/preview-v22',{recursive:true});
const server=await previewServer(),results=[],errors=[],external=[];const record=(name,detail={})=>results.push({name,pass:true,...detail});
const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH??'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,userDataDir:resolve('work/browser/v22-browser-profile'),args:['--disable-background-networking','--disable-component-update'],env:{...process.env,TEMP:resolve('work/tmp'),TMP:resolve('work/tmp')}});
try{const page=await browser.newPage();await page.setViewport({width:1500,height:1100,deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));await page.setRequestInterception(true);page.on('request',r=>{if(r.url().startsWith('http://127.0.0.1:')||r.url().startsWith('data:'))r.continue();else{external.push(r.url());r.abort();}});await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'networkidle0'});await page.evaluate(()=>localStorage.clear());await page.reload({waitUntil:'networkidle0'});await page.waitForFunction(()=>window.preview?.status().state==='active');await page.waitForSelector('#after [data-ecp-prose]');
 assert.equal(await page.evaluate(()=>window.__prettierRegistration.id),'dsh-echocat-prettier');record('packaged client executes through the DSH module loader contract');
 const baseline=await page.$eval('#before',e=>e.textContent),after=await page.$eval('#after [data-ecp-prose]',e=>e.textContent);assert.equal(after,baseline);record('original answer text is unchanged');
 const widths=await page.evaluate(()=>['before','after'].map(id=>document.querySelector('#'+id+' ._markdown_uddqf_5').getBoundingClientRect().width));assert.equal(widths[0],widths[1]);record('before and after keep equal content widths',{width:widths[0]});
 for(const preset of ['minimal','moonPearl','deepOcean']){await page.evaluate(id=>window.preview.settings.preset(id),preset);await new Promise(r=>setTimeout(r,80));assert.equal(await page.$eval('#after [data-ecp-prose]',e=>e.textContent),baseline);assert.equal(await page.$eval('#after [data-ecp-prose]',e=>e.dataset.ecpPalette),preset);record('preset '+preset+' changes appearance without changing text');}
 await page.click('.preview-sidebar-wide .ecp-sidebar-open');await page.waitForSelector('dialog[open]');const diagnostic=await page.$eval('.ecp-diagnostic textarea',e=>JSON.parse(e.value));assert.equal(diagnostic.version,'0.23.5');assert.deepEqual(Object.keys(diagnostic).sort(),['plugin','version','state','assistantRows','matchedMessages','proseBlocks','adapter'].sort());await page.keyboard.press('Escape');record('settings dialog and privacy-minimal diagnostic work');
 await page.click('.ecp-sidebar-switch');await page.waitForFunction(()=>!document.querySelector('#after [data-ecp-prose]'));assert.equal(await page.$eval('#after ._markdown_uddqf_5',e=>e.textContent),baseline);await page.click('.ecp-sidebar-switch');await page.waitForSelector('#after [data-ecp-prose]');record('disable and re-enable restore the untouched host answer');
 await page.evaluate(()=>window.preview.settings.update({autoMeme:false,memeFrequency:'off'}));await page.waitForFunction(()=>!document.querySelector('#after .ecp-meme'));await page.evaluate(()=>window.preview.settings.update({autoMeme:true,memeFrequency:'balanced'}));await page.waitForSelector('#after .ecp-meme');record('automatic meme switch works independently');
 await page.screenshot({path:resolve('deliverables/preview-v22/20260923_GPT回复美化综合验收_V22.png'),fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(external,[]);record('preview has no runtime error or external request');
}finally{await writeFile('work/v22/test-output/browser-general-results.json',JSON.stringify({version:'0.22.0',liveDSH:false,results,errors,externalRequests:external},null,2));await browser.close();await new Promise(r=>server.close(r));console.log(JSON.stringify({pass:results.length,errors,external},null,2));}
